baseurl = "https://ptieut.github.io/blog"
title = "ptieut"
theme="archie"
copyright = "© Athul"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page
publishDir = "docs"
[Params]
    mainSections = ["post"]
    intro = true
    headline = "My blog"
    description = "My blog's description"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"