baseurl = "https://ptieut.github.io/blog"
title = "ptieut"
theme = "photophobia"
publishDir = "docs"
[Params]
    mainSections = ["post"]
    intro = true
    headline = "My blog"
    description = "My blog's description"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"